# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c870c6da1eadf97a42785d6da19fb79e611d9fe1c001f4e6ec71238d1948be0bc8a20f0098d460021f671460e5346b561924748ae77f8efef01726943b05849

test:
  secret_key_base: 2dc42a9135c18f53adbb82dabce08284d3517380bb837c50b6c15315579c7221a13d4404ad172bb7b884b43ba650e66738b0cd311d8dc9b576f670e3fac19d0d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
